use crate::detectors::Detector;
use crate::utils::{checks, http::HttpResponse};

pub struct Wordfence;

impl Detector for Wordfence {
    fn name(&self) -> &'static str {
        "Wordfence"
    }

    fn detect(&self, resp: &HttpResponse) -> bool {
        if checks::body_contains(resp, "generated by wordfence") && checks::is_forbidden(resp) {
            return true;
        }

        false
    }
}

inventory::submit! {
    &Wordfence as &dyn Detector
}